#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Render the two crawlable product pages. No runtime translation dependency."""
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parent.parent
ICONS = {
 'arrow':'<path d="M5 12h14m-6-6 6 6-6 6"/>',
 'home':'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z"/>',
 'wallet':'<path d="M20 8H5a2 2 0 0 1 0-4h13v4M4 6v13a1 1 0 0 0 1 1h15V8M20 12h-5v4h5"/>',
 'mind':'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>',
 'group':'<circle cx="9" cy="8" r="3"/><path d="M3 20v-2a6 6 0 0 1 12 0v2M17 5a3 3 0 0 1 0 6m1 4a5 5 0 0 1 3 5"/>',
 'scan':'<path d="M3 8V4h5m8 0h5v4m0 8v4h-5m-8 0H3v-4M7 12h10"/>',
 'plus':'<path d="M12 5v14M5 12h14"/>',
 'coffee':'<path d="M4 8h12v8a4 4 0 0 1-4 4H8a4 4 0 0 1-4-4ZM16 9h2a3 3 0 0 1 0 6h-2M7 3v2m5-2v2"/>',
 'meal':'<path d="M4 3v5a3 3 0 0 0 6 0V3M7 3v18M20 3v18m0-18c-5 2-5 10 0 10"/>',
 'person':'<circle cx="12" cy="8" r="3"/><path d="M5 21v-2a7 7 0 0 1 14 0v2"/>',
 'sun':'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1"/>',
 'menu':'<path d="M4 7h16M4 12h16M4 17h16"/>',
 'shield':'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z"/><path d="m8 12 3 3 5-6"/>',
 'cloud':'<path d="M7 18a5 5 0 1 1 0-10 6 6 0 0 1 12 2 4 4 0 1 1 0 8Z"/>',
 'language':'<path d="M3 5h11M8 3v2m4 0c0 5-4 10-8 12m1-9c1 4 4 7 7 9m2 4 4-12 4 12m-7-4h6"/>',
 'milestone':'<path d="m12 3 8 4v10l-8 4-8-4V7Z"/><circle cx="12" cy="12" r="3"/>',
 'phone':'<rect x="6" y="2" width="12" height="20" rx="3"/><path d="M10 5h4m-3 14h2"/>',
 'history':'<path d="M3 11a9 9 0 1 1 2 7M3 4v7h7M12 7v5l3 2"/>',
 'check':'<path d="m5 12 4 4L19 6"/>',
}

def icon(name):
 return '<svg class="icon" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+ICONS[name]+'</svg>'

def render(lang):
 def t(th,en): return th if lang=='th' else en
 home='./' if lang=='th' else './en.html'
 alt='./en.html' if lang=='th' else './'
 sample=t('ภาพประกอบหน้าจอ · ข้อมูลสมมติ','Screen illustration · sample data')
 planned=t('วางแผน','Planned'); impulse=t('ฉับพลัน','Impulse')
 def chart():
  days=t(['จ','อ','พ','พฤ','ศ','ส','อา'],['M','T','W','T','F','S','S'])
  bars=''
  for day,p,i in zip(days,[300,260,160,400,380,0,0],[120,90,80,90,260,0,0]):
   bars+=f'<div class="day"><div class="day-bar"><i class="impulse" style="height:{i/8}px"></i><i class="planned" style="height:{p/8}px"></i></div><small>{day}</small></div>'
  return f'<div class="week-chart" role="img" aria-label="{t("รายจ่ายจันทร์ถึงศุกร์: 420, 350, 240, 490, 640 บาท รวม 2,140 บาท","Monday to Friday spending: 420, 350, 240, 490, 640 baht. Total 2,140 baht.")}">{bars}</div>'
 def week():
  return f'''<div class="sample-card"><div class="label">{t('การใช้จ่ายสัปดาห์นี้','This week’s spending')}</div><div class="sample-amount">฿2,140</div><div class="week-meta"><span>{t('สัปดาห์ตัวอย่าง','Sample week')}</span><span class="mono">MON — SUN</span></div>{chart()}<div class="legend"><span><i></i>{planned} <b class="mono">70%</b></span><span class="impulse"><i></i>{impulse} <b class="mono">30%</b></span></div><div class="remaining" style="margin-top:16px"><span>{t('วันนี้ใช้ได้อีก','Available today')}</span><b>฿260</b></div></div>'''
 def phone():
  return f'''<div class="phone"><div class="status"><span>9:41</span><i class="island"></i><span>100%</span></div><div class="phone-head"><div><small>{t('สวัสดีตอนเช้า','Good morning')}</small><strong>{t('มาดูวันนี้ด้วยกัน','Let’s look at today')}</strong></div><span class="avatar">{icon('person')}</span></div>{week()}<div class="pager" aria-hidden="true"><i></i><i></i><i></i></div><div class="mini-section-label">{t('รายการล่าสุด','Recent entries')}</div><div class="transaction"><span class="icon-cell">{icon('coffee')}</span><div class="row-copy">{t('กาแฟตอนเช้า','Morning coffee')}<small>{impulse} · <span class="mono">09:10</span></small></div><span class="mono">฿85</span></div><div class="transaction"><span class="icon-cell">{icon('meal')}</span><div class="row-copy">{t('มื้อกลางวัน','Lunch')}<small>{planned} · <span class="mono">12:30</span></small></div><span class="mono">฿120</span></div><div class="phone-nav" aria-hidden="true"><span class="active">{icon('home')}Home</span>{icon('wallet')}{icon('mind')}{icon('group')}<span class="plus">{icon('plus')}</span></div></div>'''
 tours=[
  ('home','Home',t('สัปดาห์นี้ในภาพเดียว','Your week, at a glance'),t('เปิดมา ก็เห็นจังหวะของตัวเอง','A little more clarity, every day.'),t('Home ใหม่รวมรายจ่ายรายสัปดาห์ หมวดหมู่ และสินทรัพย์ไว้ใกล้กัน กดดูวันที่อยากรู้ต่อได้ในแอป','The new Home brings weekly spending, categories and assets together. In the app, tap a day to look closer.'),[t('เห็นวางแผนและฉับพลันในกราฟเดียว','Planned and impulse spending on one chart'),t('ดูยอด “ใช้ได้อีก” ตามแผนของตัวเอง','See what is available under your own plan'),t('เปิดรายละเอียดจากการ์ดที่กำลังดู','Go from each card to its details')],week()),
  ('log',t('บันทึก','Quick log'),t('หลายวิธี ในปุ่มเดียว','More ways, one button'),t('เรื่องเล็ก ๆ จดได้ทันจังหวะ','Catch the little moments.'),t('เมนูบันทึกใหม่รวมทางลัดไว้ในปุ่ม + เลือกบันทึกเอง สแกนสลิป หรือนำเข้า แล้วทบทวนรายละเอียดก่อนยืนยัน','The new + menu brings entry shortcuts together. Log manually, scan a receipt or import, then review the details before confirming.'),[t('เก็บร้านค้า หมวดหมู่ และกระเป๋าที่ใช้','Keep the merchant, category and wallet together'),t('ใส่ #แท็ก เพื่อกลับมาดูเรื่องเดียวกัน','Add #tags to revisit a shared context'),t('เลือกวางแผนหรือฉับพลันด้วยตัวเอง','Choose planned or impulse for yourself')],f'''<h4>{t('บันทึกรายจ่าย','Log an expense')}</h4><div class="sample-amount">฿85</div><p class="muted">{t('กาแฟตอนเช้า','Morning coffee')}</p><div class="demo-pills" role="group" aria-label="{t('ลองเลือกมุมมองการจ่าย','Try a spending perspective')}"><button type="button" data-tag="planned" aria-pressed="true">{planned}</button><button type="button" data-tag="impulse" aria-pressed="false">{impulse}</button></div><div class="note-sample"># {t('วันทำงาน','workday')} · {t('กระเป๋าประจำวัน','Everyday wallet')}</div><p class="tag-status" role="status" data-tag-status>{t('ตัวอย่างนี้เลือก “วางแผน” — ตั้งใจไว้ก่อนจ่าย','This example is planned — intended before paying.')}</p>'''),
  ('wallet',t('สินทรัพย์','Assets'),t('เงินสด การลงทุน และหนี้','Cash, investments and debt'),t('เงินแต่ละส่วน มาอยู่ในภาพเดียวกัน','See the parts of your money together.'),t('Home การ์ดสินทรัพย์รวมเงินสดและการลงทุน พร้อมรายการที่มีผลต่อมูลค่าพอร์ต แตะแล้วเปิดหน้าการลงทุนต่อได้','Home’s assets card brings cash and holdings together with the positions moving their value. Tap through to Investments in the app.'),[t('แยกสินทรัพย์รวมออกจากมูลค่าสุทธิ','Keep total assets distinct from net worth'),t('เห็นวันที่บันทึกราคาและข้อมูลที่มีจริง','See price dates and the information available'),t('กระเป๋า บัตร และหนี้อยู่ในภาพรวมเดียว','Wallets, cards and debt in one overview')],f'''<div class="label muted">{t('สินทรัพย์รวม','Total assets')}</div><div class="sample-amount">฿283,450</div><svg class="mini-chart" viewBox="0 0 280 68" aria-hidden="true"><path d="M2 60 24 51 48 54 72 32 96 38 120 24 144 30 168 14 192 20 216 8 244 13 278 4"/></svg><div class="asset-line"><span>{t('เงินสดและบัญชี','Cash & accounts')}</span><span class="mono">฿65,000</span></div><div class="asset-line"><span>{t('การลงทุน','Investments')}</span><span class="mono">฿218,450</span></div><div class="asset-line"><span>{t('หนี้สิน','Liabilities')}</span><span class="mono">฿30,000</span></div><div class="asset-line"><span>{t('มูลค่าสุทธิ','Net worth')}</span><strong class="mono">฿253,450</strong></div>'''),
  ('mind','MindScore',t('เห็นความเปลี่ยนแปลงรายสัปดาห์','A weekly view of change'),t('ค่อย ๆ เห็นภาพ จากข้อมูลของเธอ','A picture built from your own data.'),t('MindScore รวมมุมมอง Health, Behavior และ Adaptive พร้อมเปิดดูที่มาของแต่ละตัวเลขได้','MindScore brings Health, Behavior and Adaptive into one view, with the calculation behind each number available in the app.'),[t('เริ่มเมื่อมีข้อมูลครอบคลุมอย่างน้อย 30 วัน','Starts after at least 30 days of data history'),t('คงค่ารายสัปดาห์ ไม่ขยับตามทุกรายการ','A weekly snapshot, unchanged by midweek entries'),t('ข้อมูลยังไม่พอจะแสดงสถานะเก็บข้อมูล','Shows a building state when data is not ready')],f'''<h4>MindScore</h4><div class="sample-amount">—</div><p>{t('กำลังเก็บข้อมูล','Building your picture')}</p><div class="asset-line"><span>{t('ช่วงข้อมูลตัวอย่าง','Sample data history')}</span><span class="mono">12 / 30</span></div><p class="small-note">{t('ยังไม่แสดงคะแนนจนกว่าจะมีข้อมูลถึงเกณฑ์','A score appears only once the data meets the starting requirements.')}</p><a class="text-link" href="#mindscore">{t('ดูตัวอย่างสองสถานะ','Explore both states')}{icon('arrow')}</a>'''),
  ('group',t('กลุ่มและบิล','Groups & bills'),t('แยกส่วนของแต่ละคน','Each person’s share'),t('มื้อเดียวกัน แยกบิลได้ตามคนกิน','One meal. Everyone’s own share.'),t('สร้างกลุ่มเก็บชื่อเพื่อนไว้ใช้ซ้ำ เริ่มจากใบเสร็จแล้วแบ่งเท่ากันหรือเลือกตามรายการ พร้อมดูสถานะรับเงิน','Save a local group to reuse your friends’ names. Split a receipt evenly or by dish, then keep track of money received.'),[t('รายจ่ายของเธอแยกจากส่วนที่จ่ายให้เพื่อนก่อน','Your spending stays separate from money fronted for friends'),t('บันทึกว่ารับแล้วและย้อนสถานะได้','Mark a share received and undo that status'),t('กลุ่มอยู่บนเครื่อง และสถานะไม่ได้โอนเงิน','Groups stay on this device; a status change moves no money')],f'''<h4>{t('มื้อเย็นวันศุกร์','Friday dinner')}</h4><p class="muted">{t('แบ่งเท่ากัน','Split evenly')} · <span class="mono">฿943</span></p>{''.join(f'<div class="friend"><span class="avatar">{name[0]}</span><span class="name">{name}</span><span class="mono">฿{amount}</span></div>' for name,amount in [(t('เธอ','You'),235),('Bee',236),('Nutt',236),('Fern',236)])}<p class="small-note">{t('ส่วนของเธอ 235 + จ่ายให้เพื่อนก่อน 708 = ยอดบิล 943 บาท','Your 235 + friends’ 708 = the 943 baht bill.')}</p>'''),
 ]
 tabs=''.join(f'<button class="tour-tab" type="button" id="tab-{key}" role="tab" aria-selected="{str(i==0).lower()}" aria-controls="panel-{key}" tabindex="{0 if i==0 else -1}"><span>0{i+1}</span><span><b>{title}</b><small>{sub}</small></span>{icon("arrow")}</button>' for i,(key,title,sub,*_) in enumerate(tours))
 panels=''.join(f'<div class="tour-panel" id="panel-{key}" role="tabpanel" aria-labelledby="tab-{key}" tabindex="0"><div class="tour-description"><h3>{headline}</h3><p>{body}</p><ul>'+''.join(f'<li>{point}</li>' for point in points)+f'</ul></div><div><div class="tour-demo">{demo}</div><p class="demo-caption">{sample}</p></div></div>' for key,title,sub,headline,body,points,demo in tours)
 boot="""<script>(function(){var t='light';try{var s=localStorage.getItem('ms-theme');if(s==='dark'||s==='light')t=s;else if(matchMedia('(prefers-color-scheme: dark)').matches)t='dark';}catch(e){}document.documentElement.dataset.theme=t;})();</script>"""
 source=f'''<!DOCTYPE html>
<html lang="{lang}">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- SEO:START --><!-- SEO:END -->
{boot}<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="preload" as="image" href="./assets/mascot/mind-greet.png">
<link rel="stylesheet" href="./assets/site-v2.css"><script src="./assets/site-v2.js" defer></script></head>
<body data-page="product"><a class="skip" href="#main">{t('ข้ามไปเนื้อหา','Skip to content')}</a>
<nav class="site-nav" aria-label="{t('เมนูหลัก','Main navigation')}"><div class="container nav-inner">
<a href="{home}" class="brand"><img src="./assets/icons/icon-192.png" alt="" width="40" height="40">MindSpend</a>
<div class="nav-items" id="navigation"><a href="#feat">{t('แอปโฉมใหม่','The new app')}</a><a href="#mindscore">MindScore</a><a href="#sati">สติ+</a><a href="./about.html">{t('เรื่องของเรา','Our story · TH')}</a><a href="./support.html">{t('ช่วยเหลือ','Help · TH')}</a></div>
<div class="nav-tools"><a class="language" href="{alt}" lang="{t('en','th')}" hreflang="{t('en','th')}" aria-label="{t('Read in English','อ่านภาษาไทย')}">{t('EN','ไทย')}</a><button class="theme-button" type="button" aria-label="{t('สลับธีมสว่างหรือมืด','Switch light or dark theme')}" aria-pressed="false">{icon('sun')}</button><button class="menu-button" type="button" aria-controls="navigation" aria-expanded="false" aria-label="{t('เปิดเมนู','Open menu')}">{icon('menu')}</button></div>
</div></nav>
<main id="main"><header class="hero"><div class="container hero-grid"><div class="hero-copy">
<p class="eyebrow">MindSpend · {t('บทใหม่ของเรื่องเงิน','A new chapter with money')}</p>
<h1>{t('น้องมายด์<br>เพื่อนคู่ใจ<br><em>เรื่องเงินของเธอ</em>','Meet Mind.<br>Your companion<br><em>for everyday money.</em>')}</h1>
<p class="intro">{t('ตั้งแต่กาแฟแก้วแรก ถึงภาพรวมเงินทั้งเดือน จดง่ายขึ้น เห็นชัดขึ้น และมีน้องมายด์อยู่ข้าง ๆ ในทุกจังหวะการใช้เงิน','From your morning coffee to your whole month, make room to notice your money. Easier logging, a clearer picture, and Mind by your side.')}</p>
<div class="hero-actions"><a class="button" href="#feat">{t('ดูแอปโฉมใหม่','Explore the new app')}{icon('arrow')}</a><a class="button secondary" href="#dl">{t('การดาวน์โหลด','Get MindSpend')}</a></div>
<p class="hero-meta">{icon('phone')}iPhone · iOS <span class="mono">17.6+</span> · {t('ไทย & English · มีส่วนพื้นฐานฟรี','Thai & English · Free core features')}</p></div>
<div class="hero-art"><div class="orbit" aria-hidden="true"></div>{phone()}<img class="hero-mind" src="./assets/mascot/mind-greet.png" width="180" height="180" alt="{t('น้องมายด์ ลิ่นสีเขียว เพื่อนคู่ใจของเธอ','Mind, your green pangolin companion')}"><div class="speech">{t('วันนี้มีเรื่องเงินอะไร<br>ให้เราดูด้วยกันบ้างน้า','What shall we notice<br>together today?')}</div><div class="assets-peek"><small>{t('สินทรัพย์ของเธอ','Your total assets')}</small><span class="mono">฿283,450</span></div><p class="sample-caption">{sample}</p></div></div></header>
<div class="release-strip"><div class="container release-inner">{''.join(f'<span>{icon(ic)}{label}</span>' for ic,label in [('home',t('Home ใหม่','A new Home')),('mind','MindScore'),('group',t('แบ่งบิลกับเพื่อน','Shared bills')),('milestone','Milestones'),('language',t('ไทย + English','Thai + English')),('cloud',t('iCloud เลือกเปิดได้','Optional iCloud'))])}</div></div>
<section class="section tour" id="feat"><div class="container"><div class="section-head"><div><span class="chapter-number">01 / {t('ใกล้ชีวิตขึ้นอีกนิด','A little closer to your life')}</span><h2>{t('ตั้งแต่บันทึกหนึ่งรายการ<br>ถึงภาพรวมของเธอ','From one small entry<br>to your bigger picture.')}</h2></div><p>{t('เลือกดูแต่ละมุมของแอป แล้วค่อย ๆ รู้จักสิ่งที่เปลี่ยนไป','Explore each part of the app and get to know what has changed.')}</p></div><div class="tour-layout"><div class="tour-tabs" role="tablist" aria-label="{t('สำรวจฟีเจอร์','Explore features')}">{tabs}</div><div class="tour-panels">{panels}</div></div></div></section>
<section class="section mind-section" id="mindscore"><div class="container mind-layout"><div class="mind-visual"><div class="mind-field"><canvas id="mind-field" width="720" height="720" aria-hidden="true"></canvas><div class="field-center" id="field-center"><span class="mono" id="field-value">76</span><span id="field-label">{t('สัปดาห์ตัวอย่าง','Sample week')}</span></div></div><p class="field-caption">{t('ภาพประกอบ MindScore · ข้อมูลสมมติ ไม่ใช่คะแนนของเธอ','MindScore illustration · sample data, not your score')}</p><div class="state-switch" role="group" aria-label="{t('สถานะ MindScore ตัวอย่าง','Example MindScore state')}"><button type="button" data-score-state="ready" aria-pressed="true">{t('ตัวอย่างมีข้อมูลครบ','Data ready example')}</button><button type="button" data-score-state="building" aria-pressed="false">{t('กำลังเก็บข้อมูล','Building data')}</button></div></div><div class="mind-copy"><span class="chapter-number">02 / {t('มองความเปลี่ยนแปลง','Notice what changes')}</span><h2>{t('หนึ่งสัปดาห์<br>หลายมุมให้เข้าใจ','One week.<br>More ways to understand.')}</h2><p>{t('MindScore ชวนดูสุขภาพการเงิน พฤติกรรม และการปรับตัว ผ่านตัวเลขที่เปิดดูที่มาได้ มุมไหนยังไม่มีข้อมูลก็ระบุไว้ให้เห็น','MindScore brings together financial health, behavior and adaptation, with numbers you can open to understand. Missing information stays visible.')}</p><div class="pillars" aria-live="polite"><div class="pillar"><strong>Health</strong><span class="mono" data-pillar="76">76</span><small>{t('ภาพรวมการเงิน','Your finances')}</small></div><div class="pillar"><strong>Behavior</strong><span class="mono" data-pillar="79">79</span><small>{t('จังหวะการใช้เงิน','Spending patterns')}</small></div><div class="pillar"><strong>Adaptive</strong><span class="mono" data-pillar="72">72</span><small>{t('การปรับตัว','How you adapt')}</small></div></div><p class="small-note" id="score-note">{t('เริ่มหลังมีช่วงข้อมูลอย่างน้อย 30 วัน บันทึกค่าเมื่อเปิดแอปครั้งแรกในสัปดาห์ใหม่ และคงค่านั้นตลอดสัปดาห์ ตัวเลขเป็นมุมมองจากข้อมูลที่บันทึก ไม่ใช่อันดับเครดิต','Starts after at least 30 days of data history. The first app open of a new week captures a score that stays fixed for that week. This is a view of recorded information, not a credit rating.')}</p><a class="text-link" href="./faq.html#mindscore">{t('MindScore คิดอย่างไร','How MindScore works · TH')}{icon('arrow')}</a></div></div></section>
<section class="section" id="how"><div class="container"><div class="section-head"><div><span class="chapter-number">03 / {t('อยู่ด้วยกันในทุกวัน','Here for your everyday')}</span><h2>{t('รายละเอียดเล็ก ๆ<br>ที่ทำให้เป็นของเธอ','Little details.<br>A little more you.')}</h2></div></div><div class="more-grid">{''.join(f'<article class="more-card">{icon(ic)}<h3>{title}</h3><p>{body}</p><small>{note}</small></article>' for ic,title,body,note in [('milestone','Milestones',t('เก็บช่วงเวลาที่เคยเกิดขึ้นจริง ทั้งวันที่บันทึก เป้าหมายออม และบริบทที่เขียนไว้ ย้อนกลับมาดูได้ในโปรไฟล์','A collection of moments from your own records, savings contributions and personal notes. Revisit them in Profile.'),t('รายการที่ข้อมูลยังไม่รองรับจะบอกว่ากำลังมา','Entries without a supported data source are marked coming later.')),('language',t('ไทย หรือ English','Thai or English'),t('สลับภาษาได้ในแอป พร้อมหน้าตาที่เลือกเป็นสว่าง มืด หรือตามระบบ','Switch languages in the app and choose a light, dark or system appearance.'),t('ชื่อร้าน กระเป๋า และโน้ตที่เธอเขียนยังเป็นคำของเธอ','Your own merchant names, wallets and notes stay in your words.')),('history',t('เรื่องเดียวกัน กลับมาดูได้','Return to the same story'),t('ใช้ #แท็กเชื่อมรายการ ตั้งเป้าหมายออม และเปิดดูรายจ่ายตามเดือนที่อยากเข้าใจ','Connect entries with #tags, keep savings goals, and revisit the month you want to understand.'),t('มี Widget และ Live Activity สำหรับจังหวะระหว่างวัน','Widgets and Live Activity bring a view into your day.'))])}</div></div></section>
<section class="section sati-section" id="sati"><div class="container sati-grid"><div><span class="chapter-number">04 / {t('เลือกให้เข้ากับเธอ','Choose what fits')}</span><div class="sati-title"><h2>สติ+<br>{t('ลดงานที่ทำซ้ำ','Less repeat work.')}</h2><img src="./assets/mascot/mind-king.png" width="100" height="100" alt="{t('น้องมายด์กับสติ+','Mind with Sati Plus')}" loading="lazy"></div><p>{t('เริ่มจากส่วนพื้นฐานฟรี แล้วเลือกสติ+ เมื่อต้องการเครื่องมือนำเข้า พื้นที่จัดระบบเพิ่มเติม และหน้าตาในแบบของเธอ','Start with the free core. Choose Sati Plus for import tools, more room to organize and extra ways to make the app yours.')}</p><p class="small-note">{t('มีแบบรายเดือน รายปี และตลอดชีพ ราคาและสิทธิ์ทดลองที่ใช้ได้จะแสดงในแอปก่อนยืนยันซื้อ','Monthly, annual and lifetime options. The app displays the current price and any eligible trial before you confirm a purchase.')}</p><a class="text-link" href="./faq.html#sati">{t('รายละเอียดสติ+','About Sati Plus · TH')}{icon('arrow')}</a></div><div><table class="compare-table"><caption class="eyebrow">{t('เลือกจากสิ่งที่ใช้จริง','Choose around what you use')}</caption><thead><tr><th scope="col">{t('การใช้งาน','Feature')}</th><th scope="col">{t('พื้นฐานฟรี','Free core')}</th><th scope="col">สติ+</th></tr></thead><tbody>{''.join('<tr>'+''.join(f'<{("th scope="+chr(34)+"row"+chr(34)) if i==0 else "td"}>{v}</'+('th' if i==0 else 'td')+'>' for i,v in enumerate(row))+'</tr>' for row in [(t('บันทึกเองและดูวางแผน / ฉับพลัน','Manual logging & spending perspectives'),t('มีให้ใช้','Included'),t('มีให้ใช้','Included')),(t('ประวัติที่เปิดดูได้','Browsable history'),t('3 เดือนล่าสุด','Latest 3 months'),t('ไม่จำกัด','Unlimited')),(t('หมวดหมู่ที่สร้างเพิ่ม','Custom categories'),t('8 หมวดหมู่','8 categories'),t('ไม่จำกัด','Unlimited')),(t('นำเข้าและลงสลิปอัตโนมัติ','Imports & automatic slip logging'),'—',t('มีให้ใช้','Included')),(t('ธีมและไอคอนพรีเมียม','Premium themes & icons'),'—',t('มีให้ใช้','Included'))])}</tbody></table><p class="small-note">{t('ประวัติที่เกินช่วงแสดงผลของส่วนฟรีถูกซ่อน ไม่ได้ถูกลบ','History outside the free browsing window is hidden, not deleted.')}</p></div></div></section>
<section class="section"><div class="container privacy-grid"><div><span class="chapter-number">05 / {t('ข้อมูลของเธอ','Your information')}</span><h2>{t('เธอเลือกได้<br>ว่าให้ข้อมูลไปที่ไหน','Your information.<br>Your choices.')}</h2><a class="text-link" href="./privacy.html">{t('อ่านเรื่องความเป็นส่วนตัว','Read our privacy policy')}{icon('arrow')}</a></div><div class="privacy-items">{''.join(f'<div class="privacy-item">{icon(ic)}<div><h3>{title}</h3><p>{body}</p></div></div>' for ic,title,body in [('phone',t('เริ่มต้นบนเครื่องของเธอ','Local first'),t('บันทึกและดูรายการได้โดยไม่ต้องสร้างบัญชี MindSpend','Record and review entries without creating a MindSpend account.')),('cloud',t('iCloud เลือกเปิดได้','iCloud is optional'),t('เลือกซิงก์ข้อมูลที่รองรับผ่าน iCloud ส่วนตัว กลุ่ม บิลแบ่ง และบันทึก Milestones ยังอยู่เฉพาะเครื่อง','Opt in to sync supported records through your private iCloud. Groups, shared bills and the Milestones journal remain local.')),('shield',t('AI ขอความยินยอมแยกตามฟีเจอร์','AI asks for feature-specific consent'),t('การอ่านใบเสร็จ ใบแจ้งหนี้ และคุยกับมายด์มีรายละเอียดข้อมูลที่ส่งให้ Typhoon ก่อนเลือกใช้ ปิดการยินยอมได้ในตั้งค่า','Receipt reading, statement assistance and Mind chat explain what is sent to Typhoon before you opt in. You can withdraw consent in Settings.'))])}</div></div></section>
<section class="section" id="money-guides"><div class="container"><div class="section-head"><div><p class="eyebrow">{t('อ่านไปด้วยกัน','Read along')}</p><h2>{t('เริ่มจากเรื่องที่อยากรู้','Start with a little curiosity.')}</h2></div><a class="text-link" href="./blog/">{t('บทความทั้งหมด','All articles · TH')}{icon('arrow')}</a></div><div class="guide-grid">{''.join(f'<a class="guide-card" href="./{url}"><span class="eyebrow">0{i+1}</span><h3>{title}</h3><p>{body}</p>{icon("arrow")}</a>' for i,(url,title,body) in enumerate([(t('budget-tracker-free-th.html','free-budget-tracker.html'),t('บันทึกรายรับรายจ่ายฟรี','A free start to tracking'),t('ตาราง CSV และรายละเอียดส่วนพื้นฐานของแอป','A downloadable CSV and a guide to the app’s free core.')),(t('financial-freedom-th.html','financial-freedom.html'),t('แผนเงินที่เข้ากับชีวิต','A plan that fits your life'),t('เริ่มเห็นรายรับ รายจ่าย และเป้าหมายในภาพเดียวกัน','Bring income, expenses and your goals into one picture.')),(t('spending-habits-th.html','spending-habits.html'),t('เข้าใจจังหวะการใช้เงิน','Get to know your habits'),t('ชวนมองวางแผนและฉับพลัน ผ่านตัวอย่างในชีวิตประจำวัน','Explore planned and impulse spending through everyday examples.'))]))}</div></div></section>
<section class="download" id="dl"><div class="container download-inner"><img src="./assets/mascot/mind-heart.png" width="160" height="160" alt="{t('น้องมายด์อยู่ข้างเธอ','Mind is by your side')}" loading="lazy"><div class="download-copy"><h2>{t('เรื่องเงินของเธอ<br>มีเพื่อนอยู่ข้าง ๆ แล้วนะ','A little company<br>for your money journey.')}</h2><p>{t('ดูรายละเอียดการใช้งานเวอร์ชันใหม่ หรือติดต่อทีม MindSpend เพื่อสอบถามช่องทางดาวน์โหลดสำหรับ iPhone','Explore the new experience or contact the MindSpend team for the official iPhone download channel.')}</p><div class="hero-actions"><a class="button" href="./support.html#contact">{t('สอบถามการดาวน์โหลด','Ask about downloading')}{icon('arrow')}</a><a class="button secondary" href="./changelog.html">{t('ดูสิ่งที่เปลี่ยนไป','What has changed · TH')}</a></div><small>{t('iPhone · iOS 17.6 ขึ้นไป · ดูรายละเอียดเวอร์ชันที่ได้รับในแอป','iPhone · iOS 17.6 or later · Check your installed app for its version details')}</small></div></div></section>
</main><footer class="site-footer"><div class="container"><div class="footer-grid"><div class="footer-about"><a href="{home}" class="brand"><img src="./assets/icons/icon-192.png" alt="" width="40" height="40">MindSpend</a><p>{t('น้องมายด์ เพื่อนคู่ใจ<br>ช่วยจ่ายอย่างมีสติ','Mind, your trusted companion<br>for mindful spending.')}</p></div><div class="footer-links"><strong>{t('สำรวจ MindSpend','Explore MindSpend')}</strong><a href="#feat">{t('แอปโฉมใหม่','The new app')}</a><a href="#mindscore">MindScore</a><a href="#sati">สติ+</a><a href="./changelog.html">{t('อัปเดต','Updates · TH')}</a><a href="./blog/">{t('บทความ','Articles · TH')}</a></div><div class="footer-links"><strong>{t('อยู่ตรงนี้ด้วยกัน','Here for you')}</strong><a href="./about.html">{t('เรื่องของเรา','Our story · TH')}</a><a href="./faq.html">{t('คำถามที่พบบ่อย','FAQ · TH')}</a><a href="./support.html#contact">{t('ติดต่อทีม MindSpend','Contact MindSpend')}</a><a href="./privacy.html">{t('ความเป็นส่วนตัว','Privacy · TH / EN')}</a><a href="{alt}" hreflang="{t('en','th')}">{t('English','ภาษาไทย')}</a></div></div><div class="footer-base"><span>© 2026 MindSpend · Thitipong Nonnoi · <a href="https://jovey.co/">Jovey</a></span><span>{t('เพื่อนคู่ใจ ช่วยจ่ายอย่างมีสติ','A companion for mindful spending')}</span></div></div></footer></body></html>
'''
 path=ROOT/('index.html' if lang=='th' else 'en.html')
 if path.exists():
  match=re.search(r'<!-- SEO:START -->.*?<!-- SEO:END -->',path.read_text(),re.S)
  if match: source=source.replace('<!-- SEO:START --><!-- SEO:END -->',match[0])
 return path,source

if __name__=='__main__':
 check='--check' in sys.argv
 for language in ['th','en']:
  path,content=render(language)
  if check:
   if path.read_text()!=content: raise SystemExit(f'{path.name}: render drift; run python3 scripts/render_home.py')
  else: path.write_text(content)
 print('Product pages verified.' if check else 'Product pages rendered in Thai and English.')
